### ISSUE TITLE
Pattern break breaks to the same pattern

### ISSUE THREAD

**Issue by SuperDisk** [ISSOtm/fortISSimO#8]
Pattern break `Dxx` seems to under fO, jump to the specified row on the pattern it's already playing. Under hD, it skips to the next pattern (unless overridden using a `Bxx` command).

**Comment by ISSOtm** [comment]
I think I see, I think this may be due to incorrect behaviour inferred from the *tracker*'s forcing of the row. I'll have to investigate that further, since that might require extra handling.

A related question: what should be the behaviour of `B` and `D` when looping is enabled in the tracker? Should they continue normally, stay in the current pattern, or stop playback entirely?

And for a bonus one: `Dxx` in the last pattern skips to row `xx` in the first pattern, then?

Side note to self: the `REFRESH_ROW` on line 255 should be deleted.
