### ISSUE TITLE
Set tempo problem

### ISSUE THREAD

**Issue by SuperDisk** [ISSOtm/fortISSimO#9]
There seems to be something not quite right with `Fxx` Set Tempo. For example, playing the first pattern of the sample song The Murderous Funk Machine (intro), it has a discrepancy. I've attached recordings displaying the difference, with the first channel isolated.

[funk.zip](https://github.com/ISSOtm/fortISSimO/files/10473676/funk.zip)

**Comment by ISSOtm** [comment]
I'm pretty sure the problem is that hUGEDriver has its row timer (`tick`) count *upwards*, towards `ticks_per_row`, whereas fortISSimO instead has its row timer count *downwards* from `wTicksPerRow`.

Then the difference is that a tempo change takes effect immediately on hD, but is delayed by one row on fO. The fix should simply be to overwrite `wRowTimer` at the same time as `wTicksPerRow`, but I don't know if I can spare the bytes x_x
